// <auto-generated />
namespace TabibV1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addArtialWriter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addArtialWriter));
        
        string IMigrationMetadata.Id
        {
            get { return "202109161048035_addArtialWriter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
