// <auto-generated />
namespace TabibV1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class intkey1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intkey1));
        
        string IMigrationMetadata.Id
        {
            get { return "202110042138334_intkey1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
