// <auto-generated />
namespace tabib.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class consultion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(consultion));
        
        string IMigrationMetadata.Id
        {
            get { return "202105010401259_consultion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
