// <auto-generated />
namespace tabib.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class editconsultion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editconsultion));
        
        string IMigrationMetadata.Id
        {
            get { return "202105011244352_editconsultion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
