// <auto-generated />
namespace tabib.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class editDBfirstV : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editDBfirstV));
        
        string IMigrationMetadata.Id
        {
            get { return "202104241519263_editDBfirstV"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
