// <auto-generated />
namespace tabib.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class deleteartical : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteartical));
        
        string IMigrationMetadata.Id
        {
            get { return "202104302330080_deleteartical"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
