// <auto-generated />
namespace tabib.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class password4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(password4));
        
        string IMigrationMetadata.Id
        {
            get { return "202105112042126_password4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
