// <auto-generated />
namespace tabib.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class datetimeconsultionallownull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datetimeconsultionallownull));
        
        string IMigrationMetadata.Id
        {
            get { return "202105021437229_datetimeconsultionallownull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
